name: dart_vlc_ffi
description: package:dart_vlc internal dependency package.
version: 0.2.3
homepage: https://github.com/alexmercerind/dart_vlc
repository: https://github.com/alexmercerind/dart_vlc
documentation: https://github.com/alexmercerind/dart_vlc/blob/master/README.md

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  ffi: ^2.1.3
  path: ^1.9.0

dev_dependencies:
  lints: ^5.1.0
